config/routes.rb
Rails.application.routes.draw do

  get 'menu_bar/search'

  get 'product_steps/show'

  get 'product_steps/update'

  get '/users/conversations/:id' => 'conversations#show'

  get 'video_chat/index'

  get 'video_chat/show'

  get 'menu_bar/show_users'

  get 'menu_bar/show_json'

  get 'video_chat/audio_call'

  post "/video_chat/index" => 'video_chat#index'

  get "/static_pages/update_users" => 'static_pages#update_users'

  get 'product_image/index'

  get 'product_image/new'

  get 'product_image/create'

  get 'product_image/edit'

  get 'product_image/update'

  get 'product_image/delete'

  get 'product_image/destroy'

  get 'sales/index'

  post 'sales/filter'

  get 'sales/filter'

  get 'sales/show'

  get 'sales/update'

  get 'sales/delete'

  get 'sales/destroy'

  get 'comments_product/index'

  get 'comments_product/new'

  get 'comments_product/create'

  get 'comments_product/update'

  get 'comments_product/delete'

  get 'comments_product/destroy'

  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  get 'carts/delete'

  get 'product_carts/index'

  get 'product_carts/index_backend'

  get 'product_carts/new'

  get 'product_carts/create'

  get 'product_carts/show'

  get 'product_carts/edit'

  get 'product_carts/update'

  get 'product_carts/delete'

  get 'product_carts/destroy'

  get 'product_carts/show_modal'

  post 'product_carts/filter'

  get 'product_carts/show_video'

  get 'carts/index'

  get 'carts/index_backend'

  get 'carts/show_modal'

  post 'carts/filter'

  get 'products/new'

  get 'products/edit'

  get 'products/update'

  get 'products/create'

  get 'products/destroy'

  get 'products/list_products'

  get 'products/show'

  root 'static_pages#home'

  get 'help' => 'static_pages#help';

  get 'about' => 'static_pages#about';

  get 'contact' => 'static_pages#contact';

  get 'signup' => 'users#new'

  post 'signup' => 'users#new'

  get 'login' => 'sessions#new'

	post 'login' => 'sessions#create'

	delete 'logout' => 'sessions#destroy'

  delete 'carts/delete' => 'carts#destroy'

  post 'carts_steps/address' => 'carts_steps#create';

  post "/carts/address" => 'carts#create';

  post "/carts/delivery" => 'carts#update';

  post "/carts/complete" => 'carts#update';

  post 'carts/payment' =>'carts#payment';

  post 'carts_steps/payment' =>'carts_steps#payment';

  get '/users/subregion_options' => 'users#subregion_options'

  get '/users/subcategories_options' => 'users#subcategories_options'

  get '/users/audio_call'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :posts,           only: [:create, :destroy] do
    resources :comments,      only: [:create, :destroy]
  end

  resources :users

  resources :products

  resources :relationships,   only: [:create, :destroy]

  resources :carts_steps

  resources :product_carts
  resources :comment_products
  resources :carts do
    get "delete"
  end
  resources :order_items, only: [:create, :update, :destroy]

  get 'videochat' => 'videochats#new'	

  get 'call' => 'videochats#index'

  resources :conversations do
    resources :messages
  end

  resource :profile_pictures

  resource :portraits

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :sender,  class_name: 'User'
  belongs_to :recipient, class_name: 'User'

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :involving, -> (user) do
    where("conversations.sender_id =? OR conversations.recipient_id =?",user.id,user.id)
  end

  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  layout false

  def create
    if Conversation.between(params[:sender_id],params[:recipient_id]).present?
      @conversation = Conversation.between(params[:sender_id],params[:recipient_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end

    render json: { conversation_id: @conversation.id }
  end

  def show
    @conversation = Conversation.find(params[:id])
    @reciever = interlocutor(@conversation)
    @messages = @conversation.messages
    @message = Message.new
  end

  private
  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end

  def interlocutor(conversation)
    current_user == conversation.recipient ? conversation.sender : conversation.recipient
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/show.html.erb
<div class="chatboxhead">
  <div class="chatboxtitle">
    <i class="fa fa-comments"></i>

    <h1><%= @reciever.name %> </h1>
  </div>
  <div class="chatboxoptions inline-flex">
    <!--
    <%= link_to "<i class='fa  fa-minus'></i> ".html_safe, "#", class: "toggleChatBox", "data-cid" => @conversation.id %>
    -->
    <%= link_to "<img src='/assets/chat/video_chat.png' class='img-responsive' />".html_safe, "#", onclick: "open_window('video')" %>
    &nbsp;&nbsp;
    <%= link_to "<img src='/assets/chat/call.png' class='img-responsive' />".html_safe, "#", onclick: "open_window('audio')" %>
    &nbsp;&nbsp;
    <%= link_to "<img src='/assets/chat/cancel.png' class='img-responsive' /> ".html_safe, "#", class: "closeChat", "data-cid" => @conversation.id %>
  </div>
</div>
<div class="chatboxcontent">
  <% if @messages.any? %>
      <%= render @messages %>
  <% end %>
</div>
<div class="chatboxinput">
  <input class="chatboxtextarea" type="text" data-cid="<%= @conversation.id %>" data-cuid ="<%= @current_user.id %>" data-remote="true" />
</div>

<%= subscribe_to conversation_path(@conversation) %>



<script>
    function open_window(kindofcall) {

        if (kindofcall == 'video') {
            var windowOpen = window.open("/video_chat/show", "test", "height=600,width=800");
        }
        if (kindofcall == 'audio') {
            var windowOpen = window.open("/video_chat/audio_call", "test", "height=600,width=800");
        }


    }




</script>