config/routes.rb
Rails.application.routes.draw do

  get 'menu_bar/search'

  get 'product_steps/show'

  get 'product_steps/update'

  get '/users/conversations/:id' => 'conversations#show'

  get 'video_chat/index'

  get 'video_chat/show'

  get 'menu_bar/show_users'

  get 'menu_bar/show_json'

  get 'video_chat/audio_call'

  post "/video_chat/index" => 'video_chat#index'

  get "/static_pages/update_users" => 'static_pages#update_users'

  get 'product_image/index'

  get 'product_image/new'

  get 'product_image/create'

  get 'product_image/edit'

  get 'product_image/update'

  get 'product_image/delete'

  get 'product_image/destroy'

  get 'sales/index'

  post 'sales/filter'

  get 'sales/filter'

  get 'sales/show'

  get 'sales/update'

  get 'sales/delete'

  get 'sales/destroy'

  get 'comments_product/index'

  get 'comments_product/new'

  get 'comments_product/create'

  get 'comments_product/update'

  get 'comments_product/delete'

  get 'comments_product/destroy'

  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  get 'carts/delete'

  get 'product_carts/index'

  get 'product_carts/index_backend'

  get 'product_carts/new'

  get 'product_carts/create'

  get 'product_carts/show'

  get 'product_carts/edit'

  get 'product_carts/update'

  get 'product_carts/delete'

  get 'product_carts/destroy'

  get 'product_carts/show_modal'

  post 'product_carts/filter'

  get 'product_carts/show_video'

  get 'carts/index'

  get 'carts/index_backend'

  get 'carts/show_modal'

  post 'carts/filter'

  get 'products/new'

  get 'products/edit'

  get 'products/update'

  get 'products/create'

  get 'products/destroy'

  get 'products/list_products'

  get 'products/show'

  root 'static_pages#home'

  get 'help' => 'static_pages#help';

  get 'about' => 'static_pages#about';

  get 'contact' => 'static_pages#contact';

  get 'signup' => 'users#new'

  post 'signup' => 'users#new'

  get 'login' => 'sessions#new'

	post 'login' => 'sessions#create'

	delete 'logout' => 'sessions#destroy'

  delete 'carts/delete' => 'carts#destroy'

  post 'carts_steps/address' => 'carts_steps#create';

  post "/carts/address" => 'carts#create';

  post "/carts/delivery" => 'carts#update';

  post "/carts/complete" => 'carts#update';

  post 'carts/payment' =>'carts#payment';

  post 'carts_steps/payment' =>'carts_steps#payment';

  get '/users/subregion_options' => 'users#subregion_options'

  get '/users/subcategories_options' => 'users#subcategories_options'

  get '/users/audio_call'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :posts,           only: [:create, :destroy] do
    resources :comments,      only: [:create, :destroy]
  end

  resources :users

  resources :products

  resources :relationships,   only: [:create, :destroy]

  resources :carts_steps

  resources :product_carts
  resources :comment_products
  resources :carts do
    get "delete"
  end
  resources :order_items, only: [:create, :update, :destroy]

  get 'videochat' => 'videochats#new'	

  get 'call' => 'videochats#index'

  resources :conversations do
    resources :messages
  end

  resource :profile_pictures

  resource :portraits

end

app/views/shared/_chat.html.erb
<!--<div class="container">
    <div class="row">
        <div class="col-md-5">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <span class="glyphicon glyphicon-comment"></span> Chat
                    <div class="btn-group pull-right">
                        <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown">
                            <span class="glyphicon glyphicon-chevron-down"></span>
                        </button>
                        <ul class="dropdown-menu slidedown">
                            <li><a href="http://www.jquery2dotnet.com"><span class="glyphicon glyphicon-refresh">
                            </span>Refresh</a></li>
                            <li><a href="http://www.jquery2dotnet.com"><span class="glyphicon glyphicon-ok-sign">
                            </span>Available</a></li>
                            <li><a href="http://www.jquery2dotnet.com"><span class="glyphicon glyphicon-remove">
                            </span>Busy</a></li>
                            <li><a href="http://www.jquery2dotnet.com"><span class="glyphicon glyphicon-time"></span>
                                Away</a></li>
                            <li class="divider"></li>
                            <li><a href="http://www.jquery2dotnet.com"><span class="glyphicon glyphicon-off"></span>
                                Sign Out</a></li>
                        </ul>
                    </div>
                </div>
                <div class="panel-body">
                    <ul class="chat">
                        <li class="left clearfix"><span class="chat-img pull-left">
                            <img src="http://placehold.it/50/55C1E7/fff&amp;text=U" alt="User Avatar" class="img-circle">
                        </span>
                            <div class="chat-body clearfix">
                                <div class="header">
                                    <strong class="primary-font">Jack Sparrow</strong> <small class="pull-right text-muted">
                                        <span class="glyphicon glyphicon-time"></span>12 mins ago</small>
                                </div>
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare
                                    dolor, quis ullamcorper ligula sodales.
                                </p>
                            </div>
                        </li>
                        <li class="right clearfix"><span class="chat-img pull-right">
                            <img src="http://placehold.it/50/FA6F57/fff&amp;text=ME" alt="User Avatar" class="img-circle">
                        </span>
                            <div class="chat-body clearfix">
                                <div class="header">
                                    <small class=" text-muted"><span class="glyphicon glyphicon-time"></span>13 mins ago</small>
                                    <strong class="pull-right primary-font">Bhaumik Patel</strong>
                                </div>
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare
                                    dolor, quis ullamcorper ligula sodales.
                                </p>
                            </div>
                        </li>
                        <li class="left clearfix"><span class="chat-img pull-left">
                            <img src="http://placehold.it/50/55C1E7/fff&amp;text=U" alt="User Avatar" class="img-circle">
                        </span>
                            <div class="chat-body clearfix">
                                <div class="header">
                                    <strong class="primary-font">Jack Sparrow</strong> <small class="pull-right text-muted">
                                        <span class="glyphicon glyphicon-time"></span>14 mins ago</small>
                                </div>
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare
                                    dolor, quis ullamcorper ligula sodales.
                                </p>
                            </div>
                        </li>
                        <li class="right clearfix"><span class="chat-img pull-right">
                            <img src="http://placehold.it/50/FA6F57/fff&amp;text=ME" alt="User Avatar" class="img-circle">
                        </span>
                            <div class="chat-body clearfix">
                                <div class="header">
                                    <small class=" text-muted"><span class="glyphicon glyphicon-time"></span>15 mins ago</small>
                                    <strong class="pull-right primary-font">Bhaumik Patel</strong>
                                </div>
                                <p>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare
                                    dolor, quis ullamcorper ligula sodales.
                                </p>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="panel-footer">
                    <div class="input-group">
                        <input id="btn-input" type="text" class="form-control input-sm" placeholder="Type your message here...">
                        <span class="input-group-btn">
                            <button class="btn btn-warning btn-sm" id="btn-chat">
                                Send</button>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
-->

app/views/shared/_comment_form.html.erb
<div class="col-md-12 col-lg-12 col-xs-12 col-sm-12">
  <div class="col-md-2 col-lg-2 col-xs-2 col-sm-2">
    <% if current_profile_avatar != [] %>
        <% if current_profile_avatar.picture.url.present? %>
            <%=  link_to image_tag(current_profile_avatar.picture.url, alt: 'profile photo', class: 'text-white img-circle img-responsive'), current_user %>
        <%else%>
            <%=  link_to image_tag('navbar_top/avatar_default.png', alt: 'profile photo',  class: 'img-circle img-responsive'), current_user  %>
        <%end%>
    <% else %>
        <%=  link_to image_tag('navbar_top/avatar_default.png', alt: 'profile photo',  class: 'img-circle img-responsive'), current_user  %>
    <% end %>
  </div>
  <div class="col-md-10 col-lg-10 col-xs-10 col-sm-10">
    <span class="user font_secundary_scolor font-medium">
      <%= link_to current_user.name, current_user %>
    </span>
    <p>
        <%= form_for([@post, @post.comments.build]) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>
            <div class="field">
              <%= f.text_field :content, placeholder: "Comment...", required: true, class: 'content_user' %>
            </div>
            <button type="submit" id="btn-comment" class='btn-sttatus img-responsive'>
              <%= image_tag 'post/btn_comment.png' %>
            </button>
        <% end %>

    </p>

  </div>
  <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12 font_secundary_scolor">
    <ul class="comment-menu">
      <li> <%= image_tag 'post/footer_crown.png' %><span class="hidden-xs">Sttattus</span></li>
      <li><%= image_tag 'post/footer_coment.png' %><span class="hidden-xs">Comment</span></li>
      <li><%= image_tag 'post/footer_share.png' %><span class="hidden-xs">Share</span></li>
    </ul>
  </div>


</div>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class= "posts">
    <%= render @feed_items%>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_foo.html.erb
<ul class="users">
  <% @ssfeed.each do |user| %>
      <%= render user%>
  <% end %>
</ul>

app/views/shared/_left.html.erb
<section class="stats">
        <%= render 'shared/stats' %>
      </section>
<iframe width="427" height="255" src="https://www.youtube.com/embed/DKRlWLDWhGI" frameborder="0" allowfullscreen></iframe>

app/views/shared/_navbar_top.html.erb
<div class="col-md-4 col-lg-4 col-sm-12 col-xs-12" >
    <%= form_tag '/menu_bar/show_users', method: 'get', class: 'navbar-form sn-border-color nopadding' do %>
            <div class="input-group padding-top">
          <div class="col-md-3 col-lg-3 col-sm-2 col-xs-2">
            <%= image_tag('navbar_top/logo_crown.png', alt: 'Logo Sttattus', class: 'img-responsive') %>
          </div>
          <div class="col-md-7 col-lg-7 col-sm-5 col-xs-5  margin-left-n-30">
            <input type="text" id="demo-input-local-custom-formatters" class="form-control " name="blah">
          </div>
          <div class="col-md-2 col-lg-2 col-sm-3 col-xs-3">
            <button  class="search_button" type="submit">
              <%= image_tag('navbar_top/btn_search_blue.png', alt: 'Search', class: 'img-responsive') %>
            </button>
          </div>
        </div>
    <% end %>
</div>
<div class="col-md-7 col-lg-7 col-sm-11 col-xs-11 padding_15top" >
    <ul class="nav navbar-nav ">
        <li>
          <% if current_profile_avatar != [] %>
              <% if current_profile_avatar.picture.url.present? %>
                <%=  link_to image_tag(current_profile_avatar.picture.url, alt: 'profile photo', class: 'text-white img-circle-profile img-responsive') + '  ' +
                                   current_user.name.split(' ').first,  current_user,  class: 'text-white text-center font_avatar' %>
              <%else%>
                 <%=  link_to image_tag('navbar_top/avatar_default.png', alt: 'profile photo',  class: 'img-circle-profile img-responsive') + '  ' +
                                       current_user.name.split(' ').first,  current_user, class: 'text-white text-center font_avatar'  %>
              <%end%>
          <% else %>
              <%=  link_to image_tag('navbar_top/avatar_default.png', alt: 'profile photo',  class: 'img-circle-profile img-responsive') + '  ' +
                                   current_user.name.split(' ').first,  current_user, class: 'text-white text-center font_avatar'  %>
          <% end %>
        </li>

        <li>
            <%= render 'shared/sub_categories' %>
        </li>

        <li>
          <%=  link_to image_tag('navbar_top/icon_mensage20.png', alt: 'mensage', class: 'text-white img-responsive'), root_path,
                       class: 'text-white text-center' %>
        </li>
        <li>
          <%=  link_to image_tag('navbar_top/icon_sin_notification20.png', alt: 'notification', class: 'text-white img-responsive'), root_path,
                       class: 'text-white text-center' %>
        </li>
        <li>
          <%=  link_to image_tag('navbar_top/icon_friends20.png', alt: 'friends', class: 'text-white img-responsive'), root_path,
                       class: 'text-white text-center' %>
        </li>
        <li>
          <%= link_to carts_index_path, class: 'text-white font_menu ' do %>
              <%= render 'layouts/cart_text' %>
          <% end %>
        </li>

    </ul> <!-- end ul-->
 </div>
<div class="col-md-1 col-lg-1 col-md-offset-0 col-lg-offset-0 col-sm-1 col-xs-1 padding_15top">
  <ul class="nav navbar-nav navbar-right">
    <li class="dropdown" id="arrow">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <div id="square-background">
          <%= image_tag('navbar_top/menu_bars.png', alt: 'menu bars',  class: 'img-responsive') %>
        </div>
      </a>
      <ul class="dropdown-menu most-right-ul font_secundary_scolor">
        <li><%= link_to "Profile", current_user %></li>
        <li><%= link_to "Settings", edit_user_path(current_user) %></li>
        <li class="divider"></li>
        <% if current_user.admin == true %>
            <li><%= link_to "Sales", carts_index_backend_path %></li>
            <li><%= link_to "Products", product_carts_index_backend_path %></li>
            <li><%= link_to "Log out", logout_path, method: "delete" %></li>
        <% else %>
            <li><%= link_to "Orders", carts_index_backend_path %></li>
            <li><%= link_to "Sales", sales_index_path %></li>
            <li><%= link_to "Products", product_carts_index_backend_path %></li>
            <li><%= link_to "Log out", logout_path, method: "delete" %></li>
        <% end %>
      </ul>
    </li>
  </ul> <!-- end ul right-->
</div>

<script>


    $("#demo-input-local-custom-formatters").tokenInput("/menu_bar/show_json", {
        propertyToSearch: "first_name",
        resultsFormatter: function (item) {
            return "<li>" +  "<div style='display: inline-block; padding-left: 10px;'><div class='full_name'>" + item.first_name + "</div><div class='email'>" + item.email + "</div></div></li>"

        },
        tokenFormatter: function (item) {
            return "<li><p>" + item.first_name + " <b style='color: red'>" + "</b></p></li>"
        }

    });
    $('#token-input-demo-input-local-custom-formatters').css({'color': '#565050'})
    $('#token-input-demo-input-local-custom-formatters').attr('name', 'user_to_search');



</script>

app/views/shared/_pics_modal.html.erb
<div class="modal fade" id="profile_photo_modal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" id="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
         <br />
      </div>
      <div class="modal-body">
        <%= render 'shared/profile_pics_form' %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="portrait_photo_modal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" id="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <br />
      </div>
      <div class="modal-body">
        <%= render 'shared/protrait_pics_form' %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_profile.html.erb
<div id="profile">
  <%= image_tag('rails.png', id: 'portrait') %>
  <div id="photo">
    <%= image_tag('mino.jpg', id: 'prof_photo') %>
  </div>
  <div class="col-md-2 p_icons">
    <a href="#" class=" btn-default btn-lg btn-block">
      <span class="glyphicon glyphicon-facetime-video"></span>
    </a>
  </div>
  <div class="col-md-2 p_icons">
    <a href="#" class="btn-default btn-lg btn-block">
      <span class="glyphicon glyphicon-earphone"></span>
    </a>
  </div>

  <div class="col-md-2 p_icons">
    <a href="#" class="btn-default btn-lg btn-block">
      <span class="glyphicon glyphicon-envelope"></span>
    </a>
  </div>
  <div class="col-md-2 p_icons">
    <a href="#" class="btn-default btn-block p_letters">
      About
    </a>
  </div>
  <div class="col-md-2 p_icons">
    <a href="#" class="btn-default btn-block p_letters">
      Photos
    </a>
  </div>
  <div class="col-md-2 p_icons">
    <a href="#" class="btn-default btn-block p_letters ">
      Friends
    </a>
  </div>
</div>

app/views/shared/_profile_pics_form.html.erb
<div class="row padding_top">

  <%= render 'users/new_pic_form' %>

  <%= render 'users/user_prof_pics' %>

  <%= render 'users/user_posted_pics' %>

</div>

app/views/shared/_right.html.erb
<div class="col-md-6">
<div class="sectionc">
               <div class="sectionc2_group">  
              <h4 style="background:#FFF;">Styles</h4>    
               <%= link_to image_tag( "user1.jpg", size: "15x15" ) + "Pop" %><br>
               <%= link_to image_tag( "user2.jpg", size: "15x15" ) + "Rock" %><br>
               <%= link_to image_tag( "user3.jpg", size: "15x15" ) + "Rap" %><br>
               <%= link_to image_tag( "user4.jpg", size: "15x15" ) + "Reggaeton" %><br>
               <%= link_to image_tag( "user5.jpg", size: "15x15" ) + "Jazz" %><br>
               <%= link_to image_tag( "user1.jpg", size: "15x15" ) + "Soul" %><br>                              
               <%= link_to image_tag( "user2.jpg", size: "15x15" ) + "Salsa" %><br> 
               </div>
               </div>  

<%= link_to image_tag( "publi1.jpg",  size: "165x150" ) %>

    <hr STYLE="border-width: 2px"  >

<%= link_to image_tag( "publi2.jpg",  size: "165x150" ) %>
  
      <hr STYLE="border-width: 2px"  >

<%= link_to image_tag( "publi3.jpg",  size: "165x150" ) %>
  
</div>

<div class="col-md-6">

 <aside class="sidebar fixed"> 
<!--       chat boostrap -->
 </aside>

</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
  <div class="stats">
    <a href="<%= following_user_path(@user) %>">
      <strong id="following" class="stat">
        <%= @user.following.count %>
      </strong>
      following
    </a> 
    <a href="<%= followers_user_path(@user) %>">
      <strong id="followers" class="stat">
        <%= @user.followers.count %>
      </strong>
       followers  
    </a>
  </div>   

app/views/shared/_subsubcategory.html.erb
<div class="chat-container col-md-12 col-lg-12 col-xs-12 col-sm-12 no_side_padding" id="chat-principal">
  <div class="panel-heading font_title_chat text-center">Sttattus Chat</div>
      <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12 bg-gray">
        <div class="col-md-8 col-lg-8 col-sm-8 col-xs-8">
          <input id="btn-input" type="text" class="form-control input-s">
        </div> <!-- /col -->
        <div class="col-md-4 col-lg-4 col-sm-4 col-xs-4">
          <button class="btn btn-default btn-chat-search">
            <%= image_tag 'chat/search_chat.png', title: 'Search Chat', class: 'img-responsive' %>
          </button>
        </div> <!-- col -->
      </div>
      <div class="panel-body col-md-12 col-lg-12 col-xs-12 col-sm-12">
        <ul class="users">
              <% if @subcategory.name == 'Music' %>
                <% @ssfeed.each do |sscate| %>
                  <li class="sec-3lvl-cat">
                    <div class="col-md-3 col-lg-3 col-sm-3 col-xs-3">
                        <%= image_tag 'users/icon_music_default.png', class: 'img-responsive' %>
                    </div>
                    <div class="col-md-9 col-lg-9 col-sm-9 col-xs-9">
                      <%= sscate.name %>
                    </div>
                  </li>
                <% end %>
              <% else %>
                <% @ssfeed.each do |sscate| %>
                  <li class="sec-3lvl-cat">
                    <div class="col-md-2 col-lg-2 col-sm-2 col-xs-2">
                        <button class="btn img-circle-chat-default img-responsive" ></button>
                    </div>
                    <div class="col-md-8 col-lg-8 col-sm-8 col-xs-8">
                      <%= sscate.name %>
                    </div>
                  </li>
                <% end %>
              <% end %>

        </ul>
      </div> <!--end panel-body -->
      <%= render 'video_chat/footer_chat' %>
  </div>
</div>

app/views/shared/right.html.erb
<div class="col-md-2">
</div>