config/routes.rb
Rails.application.routes.draw do

  get 'menu_bar/search'

  get 'product_steps/show'

  get 'product_steps/update'

  get '/users/conversations/:id' => 'conversations#show'

  get 'video_chat/index'

  get 'video_chat/show'

  get 'menu_bar/show_users'

  get 'menu_bar/show_json'

  get 'video_chat/audio_call'

  post "/video_chat/index" => 'video_chat#index'

  get "/static_pages/update_users" => 'static_pages#update_users'

  get 'product_image/index'

  get 'product_image/new'

  get 'product_image/create'

  get 'product_image/edit'

  get 'product_image/update'

  get 'product_image/delete'

  get 'product_image/destroy'

  get 'sales/index'

  post 'sales/filter'

  get 'sales/filter'

  get 'sales/show'

  get 'sales/update'

  get 'sales/delete'

  get 'sales/destroy'

  get 'comments_product/index'

  get 'comments_product/new'

  get 'comments_product/create'

  get 'comments_product/update'

  get 'comments_product/delete'

  get 'comments_product/destroy'

  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  get 'carts/delete'

  get 'product_carts/index'

  get 'product_carts/index_backend'

  get 'product_carts/new'

  get 'product_carts/create'

  get 'product_carts/show'

  get 'product_carts/edit'

  get 'product_carts/update'

  get 'product_carts/delete'

  get 'product_carts/destroy'

  get 'product_carts/show_modal'

  post 'product_carts/filter'

  get 'product_carts/show_video'

  get 'carts/index'

  get 'carts/index_backend'

  get 'carts/show_modal'

  post 'carts/filter'

  get 'products/new'

  get 'products/edit'

  get 'products/update'

  get 'products/create'

  get 'products/destroy'

  get 'products/list_products'

  get 'products/show'

  root 'static_pages#home'

  get 'help' => 'static_pages#help';

  get 'about' => 'static_pages#about';

  get 'contact' => 'static_pages#contact';

  get 'signup' => 'users#new'

  post 'signup' => 'users#new'

  get 'login' => 'sessions#new'

	post 'login' => 'sessions#create'

	delete 'logout' => 'sessions#destroy'

  delete 'carts/delete' => 'carts#destroy'

  post 'carts_steps/address' => 'carts_steps#create';

  post "/carts/address" => 'carts#create';

  post "/carts/delivery" => 'carts#update';

  post "/carts/complete" => 'carts#update';

  post 'carts/payment' =>'carts#payment';

  post 'carts_steps/payment' =>'carts_steps#payment';

  get '/users/subregion_options' => 'users#subregion_options'

  get '/users/subcategories_options' => 'users#subcategories_options'

  get '/users/audio_call'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :posts,           only: [:create, :destroy] do
    resources :comments,      only: [:create, :destroy]
  end

  resources :users

  resources :products

  resources :relationships,   only: [:create, :destroy]

  resources :carts_steps

  resources :product_carts
  resources :comment_products
  resources :carts do
    get "delete"
  end
  resources :order_items, only: [:create, :update, :destroy]

  get 'videochat' => 'videochats#new'	

  get 'call' => 'videochats#index'

  resources :conversations do
    resources :messages
  end

  resource :profile_pictures

  resource :portraits

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  respond_to :html, :js

  include Wicked::Wizard

  steps :address,:delivery,:payment,:complete

  def index
    @order_items = current_order.order_items
    @order = current_order
    @order_checkout = current_order
    if !current_order.address.nil?
      @address = current_order.address
    end
  else
    @address = Address.new

  end

  def index_backend

    if current_user.admin == true
      @orders = Order.all.paginate(page: params[:page], per_page: 1)
      @products_cart = ProductCart.all
      return
    end
  if current_user.admin != true
    @orders = Order.where("orders.user_id = :user_id",{user_id: current_user.id})
    @orders = @orders.paginate(page: params[:page], per_page: 2)
    return
  end
  end

  def filter
    @orders = Order.where(nil)
    if params[:initial_date].present? && params[:final_date].present?
      @orders = Order.joins(:user)
      @orders = @orders.where("orders.created_at >= :initial_date AND orders.created_at <= :final_date",
                              {initial_date: params[:initial_date], final_date: params[:final_date]})
    end

    if params[:order_status].present?
      if params[:order_status].present?
        @orders = Order.joins(:order_status)
        @orders = @orders.where("order_statuses.id = :order_status_id",
                                {order_status_id: params[:order_status]})
      end
    end



    if params[:starts_with].present?
      @orders = Order.joins(:user)
      @orders = @orders.starts_with(params[:starts_with])
    end

  end



  def edit
    @order_item = current_order.order_items.find params[:id]

  end

  def delete
    @order_item = current_order.order_items.find params[:id]
  end

  def destroy
    @order_items = current_order.order_items
    @order_item = current_order.order_items.find params[:id]
    @order_item.destroy
    redirect_to :controller => 'carts',:action => 'index'
  end

  def show
    @order_checkout = current_order
    if !current_order.address.nil?
      @address = current_order.address
      render_wizard
      return
    end
    @address = Address.new
    render_wizard
  end

  def update
    @order_checkout = current_order
    if params[:id] =='address'
      @address = current_order.address
      @address.attributes = address_params
      @address.save
      render_wizard @order_checkout
      return
    end

    if params[:id] == 'complete'
      @sale = Sale.new
      for order_item in @order_checkout.order_items do
        @sale_item = SaleItem.new
        @sale_item.product_cart = order_item.product_cart
        @sale_item.total_price = order_item.total_price
        @sale_item.quantity = order_item.quantity
        @sale_item.unit_price = order_item.unit_price
        @sale_item.sale = @sale
        @sale_item.save
      end
      printf("PUTAAAAAA #{@order_checkout.total}")
      printf("PUTAAAAAA #{@order_checkout.shipping}")
      @sale.user = current_user
      @sale.subtotal = @order_checkout.subtotal
      @sale.total = @order_checkout.total
      @sale.save
      @order_checkout.order_status_id =3
      @order_checkout.save
      # session[:order_id] =nil
      redirect_to finish_wizard_path
      return
    end


    if params[:id] == 'delivery'
      @order_checkout.shipping = params[:shipping]
      @order_checkout.delivery_company = params[:delivery_company]
      @order_checkout.total = @order_checkout.subtotal+@order_checkout.shipping
      @order_checkout.save
      render_wizard @order_checkout
      return
    end
    render_wizard @order_checkout
  end

  def create

    if !current_order.address.nil?
      redirect_to next_wizard_path
      return
    end
    @order_checkout = current_order
    @address = Address.new
    @address.attributes = address_params
    @order_checkout.address = @address
    @order_checkout.save
    redirect_to next_wizard_path
  end


  def payment
    transaction = AuthorizeNet::AIM::Transaction.new('2ysT948D2RSC', '6j569CB3jtJ36aw9',
                                                     :gateway=>:sandbox)
    credit_card = AuthorizeNet::CreditCard.new(params[:x_card_num], params[:x_card_code])
    @order_checkout = current_order
    response = transaction.purchase(@order_checkout.total, credit_card)

    if response.success?
      puts "Successfully made a purchase (authorization code: #{response.authorization_code})"
      render_wizard @order_checkout
      return
    else
      #raise "Failed to make purchase."
      render_wizard @order_checkout
      return
    end
  end


  private
  def order_params
    params.permit(:id,:order,:product_carts,:quantity)
  end

  def filtering_params(params)
    params.slice(:starts_with,:initial_date,:final_date,:order_status)
  end

  def purchase_params
    params.permit(:shipping,:delivery_company,:payment)
  end

  def address_params
    params.permit(:first_name,:last_name,:street_address,:zip_code,:phone)
  end

  def payment_params
    params.permit(:x_card_num,:x_exp_date,:x_card_code,:x_first_name,:x_last_name)
  end

  def delivery_params
    params.permit(:delivery_company,:shipping)
  end


end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart_row.html.erb
<tr>
  <td>
    <h4><%= product_cart.name %></h4>
  </td>

  <%= form_for order_item, remote: true do |f| %>
      <td>

            <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control input-small margin-bottom-20", min: 1 %>
            <%= f.hidden_field :product_cart_id, value: product_cart.id %>
            <button type="submit" class='btn-sttatus img-responsive'>
              <%= image_tag 'cars/btn_update.png' %>
            </button>

      </td>
      <td>
        <%= number_to_currency order_item.unit_price %>
      </td>
      <td>
        <h4 class="text-right"><%= number_to_currency order_item.total_price %></h4>
      </td>
      <td>
        <span class="pull-right">
            <%= link_to image_tag('cars/btn_delete.png', class: 'img-responsive'), order_item,
                        { data: { confirm: "Are you sure you wish to delete the product '#{order_item.product_cart.name}' from your cart?" },
                          method: :delete, remote: true } %>
        </span>
      </td>

  <% end %>
</tr>

app/views/carts/_complete_form.html.erb
<div class="modal-body">
  <div class="row padding_top">
    <div class="col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 col-xs-10 col-sm-10 col-sm-offset-1 col-xs-offset-1">
      <form action="/carts/complete"  method="post">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>

        <input type="hidden" name="id" value="complete">
        <div class="form-group">
            <label for="subtotal">Subtotal</label>
            <input id="subtotal" readonly="true" name="subtotal" type="text" class="form-control" value="<%= @order_checkout.total %>"/>
        </div>
        <div class="form-group">
            <label for="shipping">Shipping </label>
            <input id="shipping" readonly="true" name="shipping" type="text" class="form-control" value="<%= @order_checkout.subtotal %>"/>
        </div>
        <div class="form-group">
            <label for="total">Total</label>
            <input id="total" readonly="true" name="total" type="text" class="form-control" value="<% @order_checkout.total %>"/>
        </div>

        <input type="submit" class="btn_continue_shopping img-responsive" value="" />
      </form>
    </div>
  </div>
</div>

app/views/carts/_delete.html.erb
<div class="modal-header">
  <h3>Delete Product</h3>
</div>
<div class="modal-body">
  <ul class="errors"></ul>
  Are you sure you wish to delete <b><%= @order_item.product_cart.name %></b>?
</div>
<div class="modal-footer">
  <%= link_to "Yes, Delete This Product", order_item_path(@order_item), method: :delete, remote: true, class: "btn btn-danger" %>
  <%= link_to "No, Please Don't", "#", class: "btn", data: { dismiss: "modal" } %>
</div>

app/views/carts/_delivery_form.html.erb
      <div class="modal-body">
        <div class="row padding_top">
          <div class="col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 col-xs-10 col-sm-10 col-sm-offset-1 col-xs-offset-1">
            <form action="/carts/delivery"  method="post" data-remote="true">

              <input type="hidden" name="id" value="delivery">
              <div class="form-group">
                  <label for="delivery_company">Delivery company</label>
                  <select id="delivery_company" name="delivery_company" class="form-control">
                    <option value="UPS">UPS</option>
                    <option value="ZOOM">ZOOM</option>
                    <option value="DHL">DHL</option>
                  </select>
               </div>
              <div class="form-group">
                <label for="shipping">Shipping</label>
                <input id="shipping" placeholder="shipping price" name="shipping" type="text" class="form-control"/>
              </div>
              <input type="submit" class="btn_continue_shopping img-responsive" value="" />
            </form>
          </div>
        </div>
      </div>

app/views/carts/_index.html.erb
<div id ="cart">
    <% @order_items.each do |order_item| %>
        <tr>
          <td><%= order_item.product_cart.name %></td>
          <td><%= number_to_currency order_item.product_cart.price %></td>
          <td><%= order_item.quantity %></td>
          <td><%= link_to 'Delete',{:action => 'delete', :id => order_item.id},:confirm => 'Are you sure?',:method => :delete %></td>
        </tr>
    <% end %>
</div>

app/views/carts/_modal.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <h4 class="modal-title" id="myModalLabel">Modal title</h4>
</div>
<div class="modal-body">
  <h2>Test</h2>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
  <button type="button" class="btn btn-primary">Save changes</button>
</div>

app/views/carts/_order_row.html.erb
<% @orders.each do |order| %>
    <tr>
      <td><%= order.id %></td>
      <td><%= order.created_at.strftime("%F") %></td>
      <td><%= order.user.email %></td>
      <td><%= order.order_status.name %></td>
      <td><%= order.total %></td>

    </tr>
<% end %>

app/views/carts/_payment_form.html.erb
<div class="modal-body">
  <div class="row padding_top">
    <div class="col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 col-xs-10 col-sm-10 col-sm-offset-1 col-xs-offset-1">
      <form action="/carts/payment" method="post" data-remote="true">

        <input type="hidden" name="id" value="payment">
        <div class="form-group">
            <label for="x_card_num">Credit cart number</label>
            <input id="x_card_num"  name="x_card_num" value="4111111111111111" type="text" class="form-control"/>
        </div>
        <div class="form-group">
            <label for="x_exp_date">Exp</label>
            <input id="x_exp_date"  name="x_exp_date" value="1117" type="text" class="form-control"/>
        </div>
        <div class="form-group">
            <label for="x_card_code">CCV</label>
            <input id="x_card_code"  name="x_card_code" type="text" value="1120" class="form-control"/>
        </div>
        <div class="form-group">
            <label for="x_first_name">First Name</label>
            <input id="x_first_name"  name="x_first_name" value="Jesus" type="text" class="form-control"/>
        </div>
        <div class="form-group">
            <label for="x_last_name">Last Name</label>
            <input id="x_last_name"  name="x_last_name" value="Garcia" type="text" class="form-control"/>
        </div>
        <button type="submit" class='btn-sttatus img-responsive'>
          <%= image_tag 'cars/btn_pay.png' %>
        </button>
      </form>
    </div>
  </div>
</div>

app/views/carts/_shopping_cart.html.erb
<div class="col-md-12 col-lg-12 col-sm-12 col-xs-12 font_secundary_scolor">
    <div class="col-md-8 col-lg-8 col-md-offset-4 col-lg-offset-4 col-sm-12 col-xs-12 margin-bottom-20 margin-top-10" >
        <span class="font-xxlarge " ><%= image_tag 'navbar_top/cars.png' %> Shopping Cart</span>
    </div>
    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12" >
      <div class="row">
        <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
          <div class="table-responsive">
            <table class="table  table-hover">
              <thead>
              <tr>
                <th> Product </th>
                <th> Quantity </th>
                <th> Unit Price </th>
                <th><span class="pull-right"> Total</span></th>
                <th></th>
              </tr>
              <tbody>
                <% @order_items.each do |order_item| %>
                    <%= render 'carts/cart_row', product_cart: order_item.product_cart, order_item: order_item, show_total: true %>
                <% end %>
              </tbody>
              </thead> <!-- end thead -->
            </table> <!-- end table -->
          </div> <!-- end table responsive -->
        </div> <!-- end col 12 -->
      </div> <!-- end row -->
    </div> <!-- end col 12 -->
</div>

app/views/carts/complete.js.erb
$('#payment-modal').modal('hide')
$('#complete-modal').modal('show')

app/views/carts/delivery.js.erb
$('#checkout-modal').modal('hide')
$('#delivery-modal').modal('show')

app/views/carts/index.html.erb
<div class="modal fade" id="checkout-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <span class="font-xxlarge modal-title" id="myModalLabel">Address</span>
      </div>
       <%= render 'address_form' %>
    </div>
  </div>
</div>

<div class="modal fade" id="delivery-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <span class="font-xxlarge modal-title" id="myModalLabel">Delivery</span>
      </div>
        <%= render 'delivery_form' %>
    </div>
  </div>
</div>


<div class="modal fade" id="payment-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <span class="font-xxlarge modal-title" id="myModalLabel">Payment</span>
      </div>
      <%= render 'payment_form' %>
    </div>
  </div>
</div>


<div class="modal fade" id="complete-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <span class="font-xxlarge modal-title" id="myModalLabel">Payment</span>
      </div>
      <%= render 'complete_form' %>
    </div>
  </div>
</div>

<div class="well bg-shopping_cart">

   <%= render 'shopping_cart'  %>


  <div class="row">
    <div class ="col-md-6 col-lg-6 col-md-offset-2 col-lg-offset-2  col-sm-4 col-xs-4 col-sm-offset-2 col-xs-offset-2 ">
      <%=link_to image_tag('cars/btn_continue.png', class: 'img-responsive'),root_path  %>
    </div>

    <div class ="col-md-4 col-lg-4 col-sm-4 col-xs-4">
      <%=link_to image_tag('cars/btn_checkout14.png', class: 'img-responsive'),{:action => 'show',:id =>'address'},remote: true %>
    </div>
  </div>
</div> <!-- end  well -->

app/views/carts/index_backend.html.erb
<div class="well bg-shopping_cart">
  <div class="row">
      <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12 font_secundary_scolor">
        <div class="col-md-8 col-lg-8 col-md-offset-4 col-lg-offset-4 col-sm-12 col-xs-12 margin-bottom-20 margin-top-10" >
          <span class="font-xxlarge ">Orders</span>
        </div>
        <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12 font_secundary_scolor ">
          <form action="/carts/filter" method="post" data-remote="true">
              <div class="row">
                <div class="col-md-3 col-lg-3 col-sm-12 col-xs-12">
                  <div class="form-group">
                    <label for="final_date">Email costumer</label>
                    <input id="starts_with" placeholder="email costumer" name="starts_with" type="text" class="form-control"/>
                  </div>
                </div>

                <div class="col-md-3 col-lg-3 col-sm-12 col-xs-12">
                  <div class="form-group">
                    <label for="initial_date">Initial date</label>
                    <input id="initial_date" placeholder="initial date" name="initial_date" type="date" class="form-control"/>
                  </div>
                </div>

                <div class="col-md-3 col-lg-3 col-sm-12 col-xs-12">
                  <div class="form-group">
                    <label for="final_date">Final date</label>
                    <input id="final_date" placeholder="final date" name="final_date" type="date" class="form-control"/>
                  </div>
                </div>

                <div class="col-md-3 col-lg-3 col-sm-12 col-xs-12" >
                  <div class="form-group">
                    <label for="state">State</label>
                    <select id="order_status" name="order_status" class="form-control">
                        <option value="1">In Progress</option>
                        <option value="2">Placed</option>
                        <option value="3">Shipped</option>
                        <option value="4">Cancelled</option>
                    </select>
                  </div>
                </div>

              </div>
              <div class="row">
                <div class="col-md-3 col-lg-3 col-sm-12 col-xs-12 center">
                  <button type="submit" class='btn-sttatus img-responsive'>
                    <%= image_tag 'cars/btn_search.png' %>
                  </button>
                </div>
              </div>

            </form>
        </div> <!-- end col 12-->
        <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12 margin-top-20">
              <div class="row" >
                <div class="col-md-12 col-lg-12">
                  <div class="table-responsive">
                        <table class="table table-hover table-bordered table-striped">
                          <thead class="bg-blue text-white">
                              <tr>
                                <th>Order number</th>
                                <th>Date</th>
                                <th>Costumer</th>
                                <th>Order Status</th>
                                <th>Total</th>
                              </tr>
                          </thead>
                          <tbody class="order-index">
                            <%= render "order_row" %>
                          </tbody>
                        </table>
                        <%= will_paginate @orders %>
                </div> <!--end table responsive -->
              </div> <!-- end row -->
            </div>
          </div>
      </div> <!-- end row -->
</div> <!-- end col 12-->
</div><!-- end well -->

<script type="text/javascript">

    $('[data-behaviour~=datepicker]').datepicker({
        format: "yyyy/mm/dd"

    })
</script>

app/views/carts/payment.js.erb
$('#delivery-modal').modal('hide')
$('#payment-modal').modal('show')