config/routes.rb
Rails.application.routes.draw do

  get 'menu_bar/search'

  get 'product_steps/show'

  get 'product_steps/update'

  get '/users/conversations/:id' => 'conversations#show'

  get 'video_chat/index'

  get 'video_chat/show'

  get 'menu_bar/show_users'

  get 'menu_bar/show_json'

  get 'video_chat/audio_call'

  post "/video_chat/index" => 'video_chat#index'

  get "/static_pages/update_users" => 'static_pages#update_users'

  get 'product_image/index'

  get 'product_image/new'

  get 'product_image/create'

  get 'product_image/edit'

  get 'product_image/update'

  get 'product_image/delete'

  get 'product_image/destroy'

  get 'sales/index'

  post 'sales/filter'

  get 'sales/filter'

  get 'sales/show'

  get 'sales/update'

  get 'sales/delete'

  get 'sales/destroy'

  get 'comments_product/index'

  get 'comments_product/new'

  get 'comments_product/create'

  get 'comments_product/update'

  get 'comments_product/delete'

  get 'comments_product/destroy'

  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  get 'carts/delete'

  get 'product_carts/index'

  get 'product_carts/index_backend'

  get 'product_carts/new'

  get 'product_carts/create'

  get 'product_carts/show'

  get 'product_carts/edit'

  get 'product_carts/update'

  get 'product_carts/delete'

  get 'product_carts/destroy'

  get 'product_carts/show_modal'

  post 'product_carts/filter'

  get 'product_carts/show_video'

  get 'carts/index'

  get 'carts/index_backend'

  get 'carts/show_modal'

  post 'carts/filter'

  get 'products/new'

  get 'products/edit'

  get 'products/update'

  get 'products/create'

  get 'products/destroy'

  get 'products/list_products'

  get 'products/show'

  root 'static_pages#home'

  get 'help' => 'static_pages#help';

  get 'about' => 'static_pages#about';

  get 'contact' => 'static_pages#contact';

  get 'signup' => 'users#new'

  post 'signup' => 'users#new'

  get 'login' => 'sessions#new'

	post 'login' => 'sessions#create'

	delete 'logout' => 'sessions#destroy'

  delete 'carts/delete' => 'carts#destroy'

  post 'carts_steps/address' => 'carts_steps#create';

  post "/carts/address" => 'carts#create';

  post "/carts/delivery" => 'carts#update';

  post "/carts/complete" => 'carts#update';

  post 'carts/payment' =>'carts#payment';

  post 'carts_steps/payment' =>'carts_steps#payment';

  get '/users/subregion_options' => 'users#subregion_options'

  get '/users/subcategories_options' => 'users#subcategories_options'

  get '/users/audio_call'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :posts,           only: [:create, :destroy] do
    resources :comments,      only: [:create, :destroy]
  end

  resources :users

  resources :products

  resources :relationships,   only: [:create, :destroy]

  resources :carts_steps

  resources :product_carts
  resources :comment_products
  resources :carts do
    get "delete"
  end
  resources :order_items, only: [:create, :update, :destroy]

  get 'videochat' => 'videochats#new'	

  get 'call' => 'videochats#index'

  resources :conversations do
    resources :messages
  end

  resource :profile_pictures

  resource :portraits

end

app/models/product.rb
class Product < ActiveRecord::Base


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def list_products
    printf("list_products")
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def show
    @product = Product.find params[:id]
  end

  def edit
    @product = Product.find params[:id]
  end

  def update
    @product = Product.find params[:id]
    if @product.update_attributes(product_params)
      redirect_to :controller => 'static_pages', :action => 'home', :id => @product.id
    end
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to :action => 'show', :id => @product.id
    else
      render :action => 'new'
    end
  end

  def destroy
    printf("entre en destroy")
    @product= Product.find(params[:id]).destroy
    flash[:success] = "Product deleted"
    redirect_to :controller => 'static_pages', :action => 'home'
  end

  private

  def product_params
    params.require(:product).permit(:id,:name, :code,:stock,:price)
  end


end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
<h4>Edit product <%= @product.name %></h4>

<div class="row padding_top">
  <div class="col-md-6 col-md-offset-3 col-lg-6 col-lg-offset-3 col-sm-12 col-xs-12" >
    <%= form_for(@product) do |f| %>

        <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
            <%= f.label :code %>
            <%= f.text_field :code, class: 'form-control' %>
        </div>
        <div class="form-group">
            <%= f.label :price %>
            <%= f.text_field :price, class: 'form-control' %>
        </div>
        <div class="form-group">
            <%= f.label :stock %>
            <%= f.text_field :stock, class: 'form-control' %>
        </div>
        <button type="submit" class='btn-sttatus img-responsive'>
          <%= image_tag 'cars/btn_edit_lg.png' %>
        </button>

    <% end %>

  </div>
</div>

app/views/products/list_products.html.erb
<div  class="well bg-shopping_cart">
  <div class="row">
    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12 font_secundary_scolor">
      <div class="col-md-8 col-lg-8 col-md-offset-4 col-lg-offset-4 col-sm-12 col-xs-12 margin-bottom-20 margin-top-10" >
        <span class="font-xxlarge ">Listing Products </span>
      </div>
      <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12 font_secundary_scolor">
        <div class="table-responsive">
          <table class="table table-hover table-bordered table-striped">
              <tr>
              </tr>

              <% @products.each do |product| %>
                  <tr>
                    <%= stylesheet_link_tag "letters" %>
                    <td><%= link_to product.name, class: "test-color",:controller => 'products' ,:action => 'show' , :id => product.id %></td>
                    <td><%= link_to image_tag('cars/btn_edit.png', class: 'img-responsive'),:controller =>'products',:action =>'edit', :id => product.id %></td>
                    <td><%= link_to image_tag('cars/btn_delete.png', class: 'img-responsive'),{:controller =>'products', :action => 'destroy', :id => product.id},:method => :delete %></td>
                  </tr>
              <% end %>

          </table>
        </div>

      </div>
      <div class="col-md-12 col-lg-12 col-xs-12 col-sm-12">
        <%= link_to 'New Product', new_product_path %>
      </div>
    </div>
  </div> <!-- end row -->
</div>  <!-- end well -->



<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
  </ol>

  <!-- Wrapper for slides -->


  <div class="carousel-inner" role="listbox">

    <div class="item active">
      <td><%= link_to @products[0].name, class: "test-color",:controller => 'products' ,:action => 'show' , :id => @products[0].id %></td>
      <%= image_tag "https://mewmagazineblog.files.wordpress.com/2014/04/shakira_caratula.jpg" %>
    </div>
    <% for product in @products %>

    <div class="item">

       <td> <%= link_to product.name , class: "test-color",:controller => 'products' ,:action => 'show' , :id => product.id %></td>

      <%= image_tag "https://mewmagazineblog.files.wordpress.com/2014/04/shakira_caratula.jpg" %>
    </div>

    <%end%>



  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/products/new.html.erb
<div class="row padding_top ">

  <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12 col-md-offset-3 col-lg-offset-3 bg-white col-banner-profile " >
    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12 margin-top-10">
      <div class="col-md-4 col-lg-4 col-sm-10 col-xs-10 col-md-offset-0 col-lg-offset-0  col-sm-offset-0  col-xs-offset-0  margin-left-n-50">
        <h4> New Products </h4>
      </div>
    </div>

    <%= form_for(@product) do |f| %>

        <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
            <%= f.label :code %>
            <%= f.text_field :code, class: 'form-control' %>
        </div>
        <div class="form-group">
            <%= f.label :price %>
            <%= f.text_field :price, class: 'form-control' %>
        </div>
        <div class="form-group">
            <%= f.label :stock %>
            <%= f.text_field :stock, class: 'form-control' %>
        </div>

        <div class="col-md-6  col-lg-6 col-md-offset-3 col-lg-offset-3 col-sm-12 col-xs-12 margin-bottom-10">
          <button type="submit" class='btn-sttatus img-responsive'>
            <%= image_tag 'users/btn_save.png' %>
          </button>
        </div>

    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<h1><%=h @product.name %></h1>

<blockquote>
  <%=h @product.code %>
</blockquote>

<%= image_tag "https://mewmagazineblog.files.wordpress.com/2014/04/shakira_caratula.jpg" %>



<%= link_to 'Edit',edit_product_path, :id => @product.id %> |
<%= link_to 'Back',root_path %>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>